### ISSUE TITLE
homebridge

### ISSUE THREAD

**Issue by profx5015** [jipema/xiaomi-mijia-thermometer#1]
Hello!
Is it possible to use your plugin in homebridge?
Thanks for your answer.

**Comment by jipema** [comment]
Hi!
I don't know much about Homebridge, but if you can use Node.js with it, then you can use this lib.
Basically, this wrapper connect to the Mijia thermometers (by mac address), collect temperature, humidity and battery values, and return them through callback/promise.

**Comment by profx5015** [comment]
Thank's for your answer!
